@startuml

[*] --> MainMenu: Opens game

SaveScore --> MainMenu: Replay game

MainMenu :

MainMenu -> DisplayScores: To scoreboard
DisplayScores -> MainMenu: Back to menu


MainMenu -> GameRunning: Clicks play

state GameRunning {
  [*] --> PausedState
  PausedState --> PlayingState : Resume game
  PlayingState --> PausedState : Pause game

  PlayingState --> [*]: Timer runs out
 }

GameRunning -> SaveScore: Game ends after 5 minutes
GameRunning --> [*]: Exit

SaveScore --> [*]: Score saved and exit

@enduml
