@startuml

skinparam classAttributeIconSize 0

interface Placeable{
    +addToLayer()
    +setLocation()
}
class GameScreen {
    -gdx.TiledMap map
    -input()
    -logic()
    -draw()
}
class Building{
    -Location data
    +addToLayer()
    +setLocation()
}
class Path{
    -Location data
    +addToLayer()
    +setLocation()
}
class EventManager{
    -Event[] events
    +startEvent()
    +stopEvent()
}
class UIManager{
    -Button[] buttons
    -Hint[] hints / tips
    +addButton()
    +removeButton()
}
class BuildingManager{
    -Building[] buildings
    +createBuilding()
    +removeBuilding()
    +getBuildingCounts()
}
class PathManager{
    -Path[] paths
    +createPath()
    +removePath()
    +getPathConnections()
}
class HighlightManager{
    +updateHighlight()
    +clearHighlight()
}
class SatisfactionManager{
    satisfaction score
    +updateSatisfaction()
    +getCurrentSatisfaction()
}
class Timer{
    -float time
    +addTime()
    +getTime()
}
class ResourceManager{
    Manages money
    +getMoney()
    +addMoney()
    +subtractMoney()
}
class Button{
    +onClick()
    }
class Hint{
    +displayHint()
    }

Placeable <|.. Building
Placeable <|.. Path
GameScreen *-- BuildingManager
GameScreen *-- PathManager
GameScreen *-- HighlightManager
GameScreen *-- UIManager
GameScreen *-- SatisfactionManager
GameScreen o-- Timer
GameScreen *-- EventManager
GameScreen *-- ResourceManager
BuildingManager --o Building
PathManager --o Path

UIManager --o Button
UIManager --o Hint




@enduml
