@startuml
actor       Player       as Foo1

Foo1 -> UI : Select building
UI -> Logic : Size tiles
Logic -> Screen : Draw transparent
Foo1 -> Screen : Click to place on positioned
Screen -> Logic : Check valid
Logic -> Screen : Draw actual building


@enduml
